# Kubernetes CheCluster patch
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  components:
    cheServer:
      deployment:
        containers:
          - image: 'quay.io/che-incubator/che-server-next:next'
            imagePullPolicy: Always
            name: che-server
